name: Build Run and Test

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and Test
      run: mvn -f pom.xml test
    - name: Build and main class
      run: mvn -f ./pom.xml compile exec:java -Dexec.mainClass="Sender.InputSender"
      
    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr
    - name: build
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o receiver Receiver\*.c*
      
    - name: run
      run: ./receiver

    - name: collect coverage
      run: gcovr --gcov -r . --html --html-details -o coverage.html --print-summary

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 21
